all:
	arm-none-linux-gnueabi-gcc zlg72128_led_test.c zlg72128_lib.c -Wall -g -o zlg72128_led_test
	arm-none-linux-gnueabi-gcc zlg72128_key_test.c zlg72128_lib.c -Wall -g -o zlg72128_key_test

clean:
	rm zlg72128_led_test zlg72128_key_test -rf
